// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD53VpvivQtciIGWa-gdG1TAa90d5AOdyE',
    appId: '1:291120926282:web:7347d6cc44e81b341b60b3',
    messagingSenderId: '291120926282',
    projectId: 'book-share-d25e5',
    authDomain: 'book-share-d25e5.firebaseapp.com',
    storageBucket: 'book-share-d25e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMa0anPIh8_Tw6njT8XJTtog43jV4xiZA',
    appId: '1:291120926282:android:30868bbe1248adf61b60b3',
    messagingSenderId: '291120926282',
    projectId: 'book-share-d25e5',
    storageBucket: 'book-share-d25e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtuanEu1XY-GZiRd8XA5ZSUNtB71S-roI',
    appId: '1:291120926282:ios:51ebc1975e9479a21b60b3',
    messagingSenderId: '291120926282',
    projectId: 'book-share-d25e5',
    storageBucket: 'book-share-d25e5.appspot.com',
    iosClientId: '291120926282-7gco7khetoh27h3bc2qidlh1pee6fq67.apps.googleusercontent.com',
    iosBundleId: 'jalak.bookShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtuanEu1XY-GZiRd8XA5ZSUNtB71S-roI',
    appId: '1:291120926282:ios:51ebc1975e9479a21b60b3',
    messagingSenderId: '291120926282',
    projectId: 'book-share-d25e5',
    storageBucket: 'book-share-d25e5.appspot.com',
    iosClientId: '291120926282-7gco7khetoh27h3bc2qidlh1pee6fq67.apps.googleusercontent.com',
    iosBundleId: 'jalak.bookShare',
  );
}
